title: Dávám tomu nový zcela originální název
baseURL: https://relaxed-lalande-b4bd9e.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

